# Generated by Django 3.2.2 on 2021-05-15 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StashHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=15)),
                ('date_created', models.DateTimeField()),
                ('details', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Stash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('description', models.TextField(max_length=1000)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stash.currency')),
                ('history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stash.stashhistory')),
            ],
        ),
    ]
